name: scanneranimal
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  intl: 0.20.2
  http: ^1.0.0
  image_picker: '>=1.1.2'
  shared_preferences: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  go_router: ^16.2.0
  provider: ^6.1.2
  firebase_core: ^4.4.0
  firebase_auth: '>=5.3.3'
  cloud_firestore: '>=5.5.0'
  google_sign_in: ^6.2.1
  in_app_purchase: ^3.0.0
  in_app_purchase_storekit: 0.4.4
  in_app_purchase_android: 0.4.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/WhatsApp Image 2026-01-13 at 3.34.07 PM.jpeg
  remove_alpha_ios: true
