name: scanneranimal
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Comunicación con Google Gemini
  http: ^1.2.0
  intl: ^0.20.2
  
  # Interfaz y Navegación
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  go_router: ^16.2.0
  provider: ^6.1.2
  
  # Cámara y Almacenamiento
  image_picker: ^1.1.2
  shared_preferences: ^2.0.0
  
  # Firebase (Base de datos y Auth)
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.1
  
  # Pagos y Suscripciones (Play Store)
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.4.0+5
  in_app_purchase_storekit: ^0.4.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.0.0
  provider: ^6.1.2
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "logo_app" # Esto genera el archivo con el nombre que pusiste en el Manifest
  ios: true
  image_path: "assets/icons/logo_app.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#121212" # Recomendado: evita bordes blancos en Android
  adaptive_icon_foreground: "assets/icons/logo_app.png"
